### ISSUE TITLE
Adding Unsplash credits to hero images?

### ISSUE THREAD

**Issue by TheNewbieWoodworker** [mmistakes/jekyll-theme-basically-basic#101]
Do you have a recommend way of adding an Unsplash credit to a page image? Preferably as a link, but if not, text would be OK. Otherwise I can just add text to the image itself.

Thanks.

**Comment by mmistakes** [comment]
I didn't add image caption support to this theme, but it shouldn't be hard for you to adapt what I've done in my other themes if you're up to it.

- [Liquid source for image caption](https://github.com/mmistakes/so-simple-theme/blob/master/_includes/page-image.html#L10-L12)
- [CSS source for image caption](https://github.com/mmistakes/so-simple-theme/blob/master/_sass/so-simple/_page.scss#L41-L63)
- [Sample YAML for image caption](https://github.com/mmistakes/so-simple-theme/blob/master/example/_posts/2012-03-14-layout-hero-image.md)

**Comment by TheNewbieWoodworker** [comment]
Thanks!
