### ISSUE TITLE
Github Pages support

### ISSUE THREAD

**Issue by vitobotta** [mmistakes/jekyll-theme-basically-basic#103]
Hi! I am currently using this theme with a self hosted blog, but I'm reading about Github Pages so I am thinking of migrating my blog there. Does this theme work with Github Pages? Thanks in advance.

**Comment by mmistakes** [comment]
Yes it does. You'll need to install it using the ["remote theme" option](https://github.com/mmistakes/jekyll-theme-basically-basic#github-pages-method) which is just a simple change in your `_config.yml` file.

The theme's demo site is hosted on GitHub pages. If you look at the [`/docs` folder](https://github.com/mmistakes/jekyll-theme-basically-basic/tree/master/docs) you'll see how it is setup and configured.
