### ISSUE TITLE
Windows dev vs Deployed github page, showing date of collection without a date 

### ISSUE THREAD

**Issue by teebu** [mmistakes/jekyll-theme-basically-basic#107]
## Environment

Using: remote_theme: "mmistakes/jekyll-theme-basically-basic" with gem "github-pages"

- Basically Basic version: 1.4.4 
- Ruby gem or remote theme version: ruby 2.6.5p114 (2019-10-01 revision 67812) [x64-mingw32]
- Jekyll version: jekyll 4.0.0
- Git repository URL: https://github.com/teebu/y_blog
- GitHub Pages hosted (if yes provide URL to site): 
- Operating system: Windows 10

## Expected behavior

Locally the collections show time and date, deployed they don't. I expect it not to have it for both. 

![image](https://user-images.githubusercontent.com/5531844/66662724-37afcf00-ebfe-11e9-9829-cb82ca206967.png)

## Steps to reproduce the behavior

Serve locally and deploy to GH pages for comparison. 

## Other

Probably not a theme issue, maybe a Jekyll issue?

**Comment by mmistakes** [comment]
GitHub Pages to my knowledge is not upgraded to use Jekyll 4 yet.

This would explain why you’re getting different results locally.

Closing as this an upstream issue and not a theme issue.
