### ISSUE TITLE
Lunr not searching some pages?

### ISSUE THREAD

**Issue by TheNewbieWoodworker** [mmistakes/jekyll-theme-basically-basic#108]
I'm using version 1.4.2, although I merged changes by hand, so it's possible I missed something, but I was pretty careful... still, anything's possible.

Love the fact you added search support. Thank you so much!

Only some of my pages are being searched by Lunr. If I had to guess, I'd say it's only searching pages in the _posts" folder. I have other pages I'd like to search also.

I've gotten a lot more knowledgeable regarding how the theme works, and Jekyll/Liquid etc., and I already know JS pretty well, so if the answer ends up needing to be technical, I think I can handle it. :)

Got any ideas? Thanks.

**Comment by mmistakes** [comment]
Have a look at this file
https://github.com/mmistakes/jekyll-theme-basically-basic/blob/master/assets/javascripts/lunr/lunr.store.js

This is what Lunr uses as the search index. It currently only includes collection documents, which is why you’re only seeing posts and not `site.pages`.

**Comment by TheNewbieWoodworker** [comment]
Thanks for the reply, and I'm sorry I haven't responded sooner. It's a long story and I don't want to bore you.

I was able to get it working, although I'm sure there's a cleaner way to code it. But it works, so, yay!

Thanks again.
