### ISSUE TITLE
Magnifier icon in the “off-canvas” menu on mobile

### ISSUE THREAD

**Issue by szilardszaloki** [mmistakes/jekyll-theme-basically-basic#114]
I was wondering whether it would be possible to prevent the magnifier icon from getting into the “off-canvas” menu on mobile.
![A3D2554E-50DE-4779-A435-678D96E91424](https://user-images.githubusercontent.com/5390451/74579442-cd87ac00-4f9a-11ea-8b14-e85c3ca4a63a.jpeg)

**Comment by mmistakes** [comment]
Not with the current design no. Unless you want to play with the width of the menu and reduce it so it isn't obscured by any icons to the right.

You'd have to reduce the amount `.is--pushed` is "pushing" the content by playing with the `$sidebar-width`. It's a bit of a moving target and will likely look odd at some breakpoints.

https://github.com/mmistakes/jekyll-theme-basically-basic/blob/8e3fda710f5e47697626669a5574c63481bf2d20/_sass/basically-basic/utilities/_align.scss#L55-L62

**Comment by szilardszaloki** [comment]
If I had the night skin applied to the “off-canvas” menu, I wouldn’t have this problem. We’ll see, thanks for your help!
Awesome theme by the way! :)
