### ISSUE TITLE
Line break in post's title

### ISSUE THREAD

**Issue by szilardszaloki** [mmistakes/jekyll-theme-basically-basic#115]
Hi there,
I'd like the title of my post to split into three lines.
```
---
title: "into three lines"
categories:
...
---
```
I've been trying to do this for quite a few hours now, but didn't succeed.
Is this disabled by any chance?
Thanks a lot!

**Comment by mmistakes** [comment]
Not possible unless you want to hack the theme. Page `h1` doesn’t accept HTML, which you’d need to do line breaks.

**Comment by szilardszaloki** [comment]
Oh, I get it, the `strip_html` in `<h1 id="page-title" class="intro-title">{{ page.alt_title | default: page.title | default: site.title | markdownify | strip_html }}</h1>`. I'll rather leave it as is... Thanks!
