### ISSUE TITLE
apple_touch_icon support

### ISSUE THREAD

**Issue by thatvirtualboy** [mmistakes/jekyll-theme-basically-basic#118]
Hi there,

I've added `<link rel="apple-touch-icon" href="/assets/images/apple-touch-icon-precomposed.png">` to my index.html and even `apple_touch_icon: /assets/images/apple-touch-icon-precomposed.png` to my _config.yml but the Apple Icon when saving to iOS Homescreen isn't working. Is this supported in the current version? Thanks!

**Comment by mmistakes** [comment]
Not sure what `apple_touch_icon` is in the _config.yml. That's not something the theme handles.
I'd suggest using the [RealFaviconGenerator](https://realfavicongenerator.net/) to create all flavors of your icon. Then drop in the HTML it provides into `_includes/head.html` and the icon files in `/assets/`.

**Comment by thatvirtualboy** [comment]
Will look into it, thanks!
