### ISSUE TITLE
How to implement scrolling view of posts in the bottom 

### ISSUE THREAD

**Issue by Hax4us** [mmistakes/jekyll-theme-basically-basic#124]
How to do the same like this ( see __ALSO ON BASICALLY BASIC THEME__)  i want to achieve the same thing like __ALSO ON MY BLOG__ then scrolling view of posts

![Screenshot_2020-06-04-17-39-10-700_com android chrome](https://user-images.githubusercontent.com/30441647/83755171-c5a76100-a68a-11ea-809f-6cd45c2e03c5.jpg)

As you can in bottom , you can scroll right to left and see posts

**Comment by mmistakes** [comment]
You'll need to add some custom CSS. It's out of the scope of the theme or it's maintainers to try and teach that.

I'd suggest using your browser's web developer tools to inspect Disqus' implementation and see what CSS they use. Then try to recreate it with custom CSS in your site.
