### ISSUE TITLE
Image is not loading properly in GitHub pages but in localhost

### ISSUE THREAD

**Issue by Hax4us** [mmistakes/jekyll-theme-basically-basic#125]
## Environment

- Basically Basic version: how to find version ?
- Ruby gem or remote theme version: 
- Jekyll version: 4.0.0
- Git repository URL: https://github.com/Hax4us/blog
- GitHub Pages hosted (if yes provide URL to site): https://hax4us.github.io/blog/
- Operating system: Android

## Expected behavior

Image must be loaded 
## Steps to reproduce the behavior

Affected page : https://hax4us.github.io/blog/about/
The same page is working perfectly in localhost

**Comment by mmistakes** [comment]
You need to use the correct path for the image... if you inspect source it's looking for https://hax4us.github.io/assets/Profile.jpg` when your image is really in `/blog/assets/Profile.jpg`.

You'll need to apply `{{ site.baseurl }}` before it. This is why it works locally but not on GH where your site pages are in `/blog`.

![Screen Shot 2020-06-06 at 1 48 03 PM](https://user-images.githubusercontent.com/1376749/83950951-623d4080-a7fc-11ea-925f-791d591e0499.png)

Closing as this isn't a theme issue.

**Comment by Hax4us** [comment]
Sorry for inconvenience but i was using blogger for years but now suddenly decided to migrate to gh pages. So i dont know how things works here :).

**Comment by Hax4us** [comment]
Can you please check this 
https://github.com/Hax4us/blog/blob/master/about.markdown
I think i am doing it in wrong way

**Comment by mmistakes** [comment]
Remove `{{ site.baseurl }}` from your about.markdown file, that won't work.
Instead you need to make a small adjustment to `_includes/author` and apply a `relative_url` filter. This will add the baseurl before the path so it can resolve correctly.

https://github.com/mmistakes/jekyll-theme-basically-basic/blob/master/_includes/author#L13-L20
