### ISSUE TITLE
Menu-item delay of 75ms

### ISSUE THREAD

**Issue by velasco** [mmistakes/jekyll-theme-basically-basic#131]
Hi, I want to switch off the delayed appearance of the menu items once it opens. I searched a lot, but I cannot find the corresponding css code. Would you help?

**Comment by mmistakes** [comment]
That's done via JavaScript, which staggers a delay to each menu item by 75ms.

https://github.com/mmistakes/jekyll-theme-basically-basic/blob/master/assets/javascripts/main.js#L18-L26
