### ISSUE TITLE
Download as PDF didn't work as expect

### ISSUE THREAD

**Issue by shingjan** [mmistakes/jekyll-theme-basically-basic#132]
## Environment

- Basically Basic version:
- Ruby gem or remote theme version:
- Jekyll version:
- Git repository URL:
- GitHub Pages hosted (if yes provide URL to site):
- Operating system:

## Expected behavior

Either in my fork or in the example page, the button on the CV page, "Download as PDF", points to "#pdf-asset" but nothing pops up. Is that bcoz no pdf was linked? Could this button be made dynamic that everytime it is clicked a PDF is generated and ready to download?

**Comment by mmistakes** [comment]
Jekyll nor this theme generates PDFs. It's up to you to create the PDF and then link to it. `#pdf-asset` is just a placeholder URL that you need to change to point to the actual location of said PDF.
