### ISSUE TITLE
Pagination no longer works.

### ISSUE THREAD

**Issue by ansonl** [mmistakes/jekyll-theme-basically-basic#24]
Pagination does not seem to be working anymore after github-pages gem version 146/147 or the most recent commit for this repo. I just noticed that pagination for my repo site stopped working after I merged with the most recent commit for this repo. 

Should the example website at [https://mmistakes.github.io/jekyll-theme-basically-basic/](https://mmistakes.github.io/jekyll-theme-basically-basic/) be displaying pagination? 
I tried cloning and downloading a copy of the repo and following the steps to enable pagination and could not get pagination to work. Reverting to github-pages v145 with `gem install github-pages -v 145` makes no difference. Maybe I am wrong about the example site? 

Not sure if this is somehow related to the `gems` to `plugins` text change specifically or to the github-pages gem. 

Thanks.

**Comment by mmistakes** [comment]
Looks like it's the `gems` to `plugins` change. I was bit by these before on another of my themes. Figured it actually made its way to GitHub Pages since it looks like they support Jekyll 3.5.1 now, but doesn't seem to be the case.

Thanks for catching this.

**Comment by mmistakes** [comment]
I'm wondering if something else is at play related to the github/github-pages update that happened today.

I just tried building the demo site locally with the lastest gems using both `gems:` and `plugins:` and neither work. `jekyll-feed`and `jekyll-sitemap` activate and work as expected, but `jekyll-paginate` does not. I know it's older and not being maintained so there's a potential it needs a small adjustment to work.

**Comment by mmistakes** [comment]
Ok figured it out. There were a few spots in the theme where I was checking for `site.gems` to determine if pagination and `jekyll-feed` were active. Had to switch those `site.plugins` as well.

[Here's the fix](https://github.com/mmistakes/jekyll-theme-basically-basic/commit/1c571dbf6c62bd911f629511cce90f3acfae4cd1).

**Comment by ansonl** [comment]
Thanks for finding the fix quickly! Great theme!
