### ISSUE TITLE
Page build warning when host to Github-Page

### ISSUE THREAD

**Issue by reysec** [mmistakes/jekyll-theme-basically-basic#25]
I get email from github when push git to github

> The page build completed successfully, but returned the following warning for the `master` branch:
> 
> You are attempting to use a Jekyll theme, "jekyll-theme-basically-basic", which is not supported by GitHub Pages. Please visit https://pages.github.com/themes/ for a list of supported themes. If you are using the "theme" configuration variable for something other than a Jekyll theme, we recommend you rename this variable throughout your site. For more information, see https://help.github.com/articles/adding-a-jekyll-theme-to-your-github-pages-site/.

How to deal with that? Am i missing something?

**Comment by mmistakes** [comment]
Remove `theme: jekyll-theme-basically-basic` from your _config.yml file as the email from GitHub suggests. 

They do not support 3rd party "theme gems" presently. You can continue using the theme as it works with the "[repo fork method](https://github.com/mmistakes/jekyll-theme-basically-basic/blob/master/README.md#github-pages-compatible-method)".
