### ISSUE TITLE
create or generate cv into pdf

### ISSUE THREAD

**Issue by reysec** [mmistakes/jekyll-theme-basically-basic#26]
Is it possible to generate cv.json into pdf when i click 'download as pdf'?
How to do that?

**Comment by mmistakes** [comment]
You'll have to find a service or app to do that. The theme doesn't generate a PDF, just allows you to link to one.

**Comment by Wigdo** [comment]
I'm having a bit of trouble figuring out how to link to a pdf, any tips would be much appreciated : )

**Comment by mmistakes** [comment]
@Wigdo I'd suggest checking out some Markdown and Jekyll help/resource sites. This isn't something specific to the theme.

You'd link to a PDF file the same as you would for any other thing (page, image, whatever).

In Markdown that would look something like:

```markdown
[link text](path-to-your-file.pdf)
```
