### ISSUE TITLE
github page build warning

### ISSUE THREAD

**Issue by horstschroeder** [mmistakes/jekyll-theme-basically-basic#27]
Hi, 
I forked your theme in my own repository to build a personal ghPage. All went well, but everytime the page is built I will reiceive an email from github with following content:

> Subject: [horstschroeder/horstschroeder.github.io] Page build warning

> The page build completed successfully, but returned the following warning for the `master` branch:
> 
> You are attempting to use a Jekyll theme, "jekyll-theme-basically-basic", which is not supported by GitHub Pages. Please visit https://pages.github.com/themes/ for a list of supported themes. If you are using the "theme" configuration variable for something other than a Jekyll theme, we recommend you rename this variable throughout your site. For more information, see https://help.github.com/articles/adding-a-jekyll-theme-to-your-github-pages-site/.
> 
> For information on troubleshooting Jekyll see:
> 
>   https://help.github.com/articles/troubleshooting-jekyll-builds

Any ideas ??
Regards 
Horst

**Comment by mmistakes** [comment]
That warning is letting you know that GitHub Pages doesn't support 3rd party themes. Just remove `theme: jekyll-theme-basically-basic` from your `_config.yml` and the warning and email will stop.
