### ISSUE TITLE
Section of menu bar is showing on the bottom of the page

### ISSUE THREAD

**Issue by Jesse-Culver** [mmistakes/jekyll-theme-basically-basic#31]
At the bottom of the pages you can see part of the menu bar (gradient part).

![image](https://user-images.githubusercontent.com/14971400/30778742-2d73c224-a0a3-11e7-9c38-11f331f45398.png)

**Comment by mmistakes** [comment]
To help track down this bug, what browser are you using?

Chrome's not showing it for me.

**Comment by Jesse-Culver** [comment]
Firefox

**Comment by mmistakes** [comment]
Thanks, I'm seeing it too.

It also appears to show up in Safari when scrolling past bottom edge of the viewport.
