### ISSUE TITLE
webs shows blank

### ISSUE THREAD

**Issue by TurbulenceHlr** [mmistakes/jekyll-theme-basically-basic#33]
when I copy and paste your ／docs files 
looks like this 
![2017-10-19 4 12 52](https://user-images.githubusercontent.com/30150851/31760846-a59b0eec-b47b-11e7-82b4-dc3acf2f827b.png)
 then the webs goes to blank

**Comment by mmistakes** [comment]
You didn't copy/paste correctly. You're missing `layout: home`. You have `layout: `.

Without the layout specified its not going to work. I'd suggest reading up on how Jekyll works, it might help you with some of this.

https://jekyllrb.com/
