### ISSUE TITLE
A data file cant be found

### ISSUE THREAD

**Issue by TurbulenceHlr** [mmistakes/jekyll-theme-basically-basic#34]
![2017-10-19 8 39 17](https://user-images.githubusercontent.com/30150851/31771162-ad5b8844-b4a0-11e7-997d-e96782461a21.png)
Seems everything goes well.But I cant found the source code that the right shows.Its a picture in your example.But on my page its just a code.Could you tell me how to solve it?
thx again

**Comment by mmistakes** [comment]
You haven't set up an author. 

https://github.com/mmistakes/jekyll-theme-basically-basic#author

**Comment by TurbulenceHlr** [comment]
thank you for supporting . I do dare say this theme is the most attracting.
