### ISSUE TITLE
More Social Media Links via Sidebar

### ISSUE THREAD

**Issue by ConnorPatterson** [mmistakes/jekyll-theme-basically-basic#35]
Apologies if this should be straightforward, I'm new to Jekyll and playing around with your example project, just trying to quickly determine if I can add more social media links to the side navigation bar besides the email, twitter, github and rss feed that come as the default.  For instance, modifying the config.yml to the following:

 author:
  name: Dugan Nash
  twitter: Towlette_Pettetucci
  facebook: Towlette_Pettetucci
  picture: https://api.adorable.io/avatars/285/johndoe.png
twitter_username: Towlette_Pettetucci
github_username: Towlette_Pettetucci
facebook_username: Towlette_Pettetucci
logo: /assets/icons/basically-basic-logo-light.svg

does not add a facebook link, so I am assuming there is no support for adding more links to the sidebar through the config, and I would have to write a rule in somewhere to populate the navigation sidebar with a facebook icon and link?  Could anyone point me in the correct direction for accomplishing this?

**Comment by mmistakes** [comment]
That's correct, it only supports Twitter and GitHub.

I built it as a replacement for Jekyll's default theme Minima, and that's all they include. If you want to add additional social networking links you can edit [`_includes/contact-list.html`](https://github.com/mmistakes/jekyll-theme-basically-basic/blob/master/_includes/contact-list.html).

The icons are built using SVG so you'd need to add those as well.
