### ISSUE TITLE
An Error?

### ISSUE THREAD

**Issue by obsession707** [mmistakes/jekyll-theme-basically-basic#38]
when i changing the content of index.md 

> ---
layout: home
paginate: true
alt_title: "Res0liya"
sub_title: "To be or not to be"
image: /assets/images/amine-ounnas-180287.jpg

introduction: |
balalalalalala....
actions:
  - label: "My Github"
    icon: github
    url: ""
  - label: "Download"
    icon: download
    url: ""
---

and i find that when the quality of **paginate** is **true**,there are no posts in the html and no button which leads to next page (i'm thinking those posts are not generated in the .html) and when i set it **false** then those posts come out... i don't know where it's my wrong operation or there lie a bug.

**Comment by obsession707** [comment]
the reason why i mosaic my introduction is purely because i am shy...

![image](https://user-images.githubusercontent.com/19381903/33069542-d64aee0c-ceef-11e7-85aa-b7789a4586f6.png)

**Comment by mmistakes** [comment]
Double check the theme's documentation... https://github.com/mmistakes/jekyll-theme-basically-basic#pagination

File needs to be `index.html` not `.md`. Jekyll's pagination plugin doesn't work with Markdown files. Rename your file and it should work.

If not you can look at the demo site's [homepage source](https://github.com/mmistakes/jekyll-theme-basically-basic/blob/master/docs/index.html) to compare.

**Comment by obsession707** [comment]
i am so sorry for that i did not find that part, i thought that .md is the import configuration file for home page, and so i remove the .html's content into my .md and delete it. So the problem following is also the same reason?
![image](https://user-images.githubusercontent.com/19381903/33082505-ebdb7b4c-cf17-11e7-83f2-97e24fb3a043.png)
i am trying to not bother you and waste your time if it's my reason, cause' this problem have trouble me for so many hours~ thanks a lot!

**Comment by mmistakes** [comment]
You likely have `theme: jekyll-theme-basically-basic` in your **_config.yml**.

Just remove that and the warning will go away. GitHub Pages doesn't support Jekyll themes setup this way so it's just warning you about that.
