### ISSUE TITLE
How to update

### ISSUE THREAD

**Issue by mappuji** [mmistakes/jekyll-theme-basically-basic#43]
I've been using this theme since long ago feeling comfortable about it and think what is the best way to upgrade the version of my theme to the latest version without breaking things. Is there is a docs for that?

**Comment by mmistakes** [comment]
Depends on what method you used to install.

If you're using it as a Ruby gem you just need to run `bundle update` to upgrade.

If you're using as a remote theme it'll automatically update when you push a new commit and GitHub Pages rebuilds your site.

If you forked the theme it's not so easy. You'll need to pull from this repo, merge in the latest changes and reconcile any merge conflicts.
