### ISSUE TITLE
Adding font declarations in theme.yml only reflected in <link>

### ISSUE THREAD

**Issue by alistaircom** [mmistakes/jekyll-theme-basically-basic#44]
I tried adding the following:

```
google_fonts:
  - name: "Libre Franklin"
    weights: "300,400,400i,700,700i"
```

to ```_data/theme.yml``` and while I can see they are being loaded, they are not reflected in the CSS. 

I presume this means I will need to change all the CSS to reflect the new font-face?

**Comment by mmistakes** [comment]
That is correct. This only loads three Google font in the`<head>`. It doesn't touch the font declarations in the SCSS files.
