### ISSUE TITLE
Not seeing the posts

### ISSUE THREAD

**Issue by TheNewbieWoodworkerDev** [mmistakes/jekyll-theme-basically-basic#46]
I'm sure I'm doing something stupid. I'm new to this. Anyway, I changed a minima-based site to your theme, and everything seems to work except I'm not seeing any posts. I just *know* it'll be obvious, but unfortunately, I'm still stuck. Any ideas? Thanks.

https://github.com/TheNewbieWoodworkerDev/TheNewbieWoodworkerDev.github.io

By the way, this is an awesome theme, and *exactly* what I wanted... well, when I finally see posts... :). Thanks so much for your efforts!

**Comment by mmistakes** [comment]
You need to rename `index.md` to `index.html`. Jekyll's pagination (which is use in the `home` layout requires a HTML file... it won't work with Markdown files).

You'll probably have to configure pagination too, see docs for how to do that.

https://github.com/mmistakes/jekyll-theme-basically-basic#pagination

**Comment by TheNewbieWoodworkerDev** [comment]
Thank you so much! I just knew it was stupid. First rule: if something doesn't work, put it back to the original version. Dang! Sorry I didn't figure this out myself, but thanks again for the quick turnaround. Love the theme.
