### ISSUE TITLE
Question: jQuery requirement

### ISSUE THREAD

**Issue by thomasjsn** [mmistakes/jekyll-theme-basically-basic#49]
Hey, what addition in the latest release requires jQuery? I've managed to make due without it, and hoping to keep it that way.

**Comment by mmistakes** [comment]
It's there for search. If you're not using that you can safely remove it.

**Comment by thomasjsn** [comment]
I am currently using Algolia for search on my site, and would like to use the search icon and search page that the latest release contains. Would I need jQuery for that?

**Comment by mmistakes** [comment]
Yes you'll need jQuery, unless you want to [rewrite this search toggle script](https://github.com/mmistakes/jekyll-theme-basically-basic/blob/master/assets/javascripts/main.js#L59-L67) in vanilla JS.

```javascript
// Search toggle
$(".search-toggle").on("click", function() {
  $(".search-content").toggleClass("is--visible");
  $(".initial-content").toggleClass("is--hidden");
  // set focus on input
  setTimeout(function() {
    $("#search").focus();
  }, 400);
});
```

I'll probably get to redoing it at some point to remove the extra dependency. Happy to merge a PR if someone wants to tackle it for me.

**Comment by thomasjsn** [comment]
I see, thanks for the reply. I think I'll just use /search as I do now, with the search icon as a link and the new search results html you added :)

**Comment by thomasjsn** [comment]
I've looked a bit more that this, wouldn't this be enough; https://stackoverflow.com/a/19075558? I'll be experimenting a bit with it...

**Comment by mmistakes** [comment]
Yeah it shouldn't be too difficult. I'm already doing [something similar](https://github.com/mmistakes/jekyll-theme-basically-basic/blob/master/assets/javascripts/main.js#L29-L39).

I pulled most of the logic from one of my other themes, which has the jQuery dependency. I just didn't have time to go in and rewrite things to be vanilla for this theme.

**Comment by thomasjsn** [comment]
I see, thanks for the feedback. Your theme and writing about Jekyll saved me so much time making my site, thank you.

**Comment by mmistakes** [comment]
Fixed in https://github.com/mmistakes/jekyll-theme-basically-basic/commit/771657756f5ab92bbfa139081b04827c1c24799f
