### ISSUE TITLE
I was wondering about the Search Feature

### ISSUE THREAD

**Issue by 14u2ponder** [mmistakes/jekyll-theme-basically-basic#50]
I really think your search function is awesome, is there any chance you'd be willing to show the basics of what I need to implement it into other themes. What files.

I think it would be an awesome plug-in to many themes.

**Comment by mmistakes** [comment]
Sure. There are two ways the theme uses search.

First one builds a [JSON file](https://github.com/mmistakes/jekyll-theme-basically-basic/blob/master/assets/javascripts/search-data.json) that contains all documents in the site, indexing their categories, tags, and content. Then using [Lunr](https://lunrjs.com/) it [outputs results](https://github.com/mmistakes/jekyll-theme-basically-basic/blob/master/_includes/search/lunr-search-scripts.html) based off the JSON file.

The other option uses [Algolia](https://www.algolia.com/) via the [jekyll-algolia](https://github.com/algolia/jekyll-algolia) plugin.

**Comment by 14u2ponder** [comment]
Hey thanks for the quick feedback. What I was really asking though is for the CSS, off canvas stuff if I were going to implement this into minimal for example.
I know this uses lunr. But your customization is what makes this search function so special.

**Comment by 14u2ponder** [comment]
I meant minima theme or white glass.

**Comment by mmistakes** [comment]
It's all in the theme files. Just poke around the JS and `_sass`. I'm not doing anything magically. 

When the search button is clicked it [reveals the search input field and results `div`](https://github.com/mmistakes/jekyll-theme-basically-basic/blob/master/assets/javascripts/main.js#L63-L74) by toggling some classes.
