### ISSUE TITLE
Hero image enhancement 

### ISSUE THREAD

**Issue by 14u2ponder** [mmistakes/jekyll-theme-basically-basic#51]
On my 27 in monitor, 2k resolution, the hero image takes up the entire screen. At other smaller widths, the hero image looks perfect. It is only when you fullsize a 27 in screen like mine that the image is overwhelming. 

![basically](https://user-images.githubusercontent.com/4943529/36928915-0e8f1072-1e50-11e8-9491-10cd13385084.png)

**Comment by mmistakes** [comment]
First world problems 🤷‍♂️

**Comment by ammianus** [comment]
I was wondering if there is any suggested way to customize this to limit the height of the image to some maximum?

I am on 15" Macbook and the same thing happens if I just have a browser using most of the Mac's desktop (by default), otherwise it looks good when using a narrow window.
