### ISSUE TITLE
posts URL

### ISSUE THREAD

**Issue by kerner1000** [mmistakes/jekyll-theme-basically-basic#52]
How can I omit the date in the posts URL? E.g:

`https://me.github.io/blog/2018/03/05/fritz`

should be 

`https://me.github.io/blog/fritz`

**Comment by mmistakes** [comment]
You can control this via `permalink` in your _config.yml

Closing as this is a Jekyll thing you can inquire with then if you need more assistance.

Ref: https://jekyllrb.com/docs/permalinks/

**Comment by kerner1000** [comment]
Perfect! Thanks for the immediate response!
