### ISSUE TITLE
Single post in another lang

### ISSUE THREAD

**Issue by kerner1000** [mmistakes/jekyll-theme-basically-basic#53]
Can I override the global lang settings for a single post?
E.g.:

```
---
layout: post
title: "Ein Post in einer anderen Spache"
categories: [blog]
tags: [t1, t2]
author: kerner1000
comments: true
share: true
lang: de-de
---
```

**Comment by mmistakes** [comment]
No, this is out of scope for the theme. You'll need to do customize theme and/or use i18n Jekyll plugins to do it.

Closing as this is out of scope for this theme. Here are some references to get you started:

- https://www.sylvaindurand.org/making-jekyll-multilingual/
- http://chocanto.me/2016/04/16/jekyll-multilingual.html
- https://github.com/untra/polyglot
- https://github.com/liamzebedee/jekyll-i18n
- https://github.com/Anthony-Gaudino/jekyll-multiple-languages-plugin
- http://jekyll-langs.liaohuqiu.net/

**Comment by kerner1000** [comment]
I installed Polygot, seems to work easily!


 From the SEO tag
```
<meta property="og:locale" content="de" />
```

Many thanks!
