### ISSUE TITLE
index filtered by tag or category

### ISSUE THREAD

**Issue by kerner1000** [mmistakes/jekyll-theme-basically-basic#54]
Is there a way to serve requests like
`me.github.io/blog/[categoryname-or-tag-name]`
in a way that looks just like the root index but shows posts filtered by given category name or tag name?

**Comment by mmistakes** [comment]
Depends on where you're hosting your site.

If its anywhere except GitHub Pages you can use the [Jekyll Archives plugin](https://github.com/jekyll/jekyll-archives) to create category and tag archive pages that list all posts assigned to those taxonomies.

It you're hosting on GitHub Pages then you'll have to manually create pages for each category or tag, or use a service like Travis CI to build your site and push the compiled files back to GH.

As this isn't a theme related issue and is more of "how to use Jekyll" you'll need to ask for further help through one of their [approved channels](https://jekyllrb.com/help/).

**Comment by mmistakes** [comment]
Pagination only works at the root level, it's a limitation of Jekyll's pagination.

You'll need to i[nstall a different plugin](https://github.com/sverrirs/jekyll-paginate-v2) if you want to paginate multiple category or tag pages in addition to the homepage. But again, this won't work if you're hosting on GitHub Pages as they don't allow you to install 3rd party plugins.

**Comment by kerner1000** [comment]
OK, many thanks for helping!
