### ISSUE TITLE
Add toggle for intro image color overlay

### ISSUE THREAD

**Issue by Weiming-Hu** [mmistakes/jekyll-theme-basically-basic#55]
Hi there,

Do you have any idea why the intro image has a slightly different color? Look likes it has some sort of a mask on it.

[The website](https://weiming-hu.github.io/)

[The original jpeg](https://github.com/Weiming-Hu/Weiming-Hu.github.io/blob/master/assets/images/qamdo-China.jpg)

Thank you
Weiming

**Comment by mmistakes** [comment]
That's correct, there is a an overlay to unify the colors. Here's the [relevant CSS line](https://github.com/mmistakes/jekyll-theme-basically-basic/blob/master/_sass/basically-basic/_intro.scss#L22) if you want to remove it.

At some point I'll add a toggle to disable.

**Comment by Weiming-Hu** [comment]
Awesome.  Thank you!

**Comment by mmistakes** [comment]
This is now fixed on `master`. Add the following to your CSS to disable the color overlay:

```scss
$intro-image-color-overlay: false;
```

**Comment by Weiming-Hu** [comment]
Thank you!
