### ISSUE TITLE
Display tags or categories

### ISSUE THREAD

**Issue by Weiming-Hu** [mmistakes/jekyll-theme-basically-basic#56]
Hi there,

Could you please explain what's the purpose of having category or tags except for the convenience of search? And what would be a good practice to use them?

Thank you

**Comment by mmistakes** [comment]
To group content and/or list posts attributed to them.

For example if you had posts about "Jekyll" you could tag them and build a tag page that lists all of those posts.

Same thing for categories. Both are purely optional and just added ways of grouping your content into taxonomies.

**Comment by Weiming-Hu** [comment]
Exactly. Thank you!

Do you have a demo showing how to create a tag page that lists all of the posts with the tag?

And I assume this tag page will appear in the hidden left panel, right?

**Comment by mmistakes** [comment]
Not with this theme I don’t have any examples. Check out my other theme to see one.

https://github.com/mmistakes/so-simple-theme

**Comment by Weiming-Hu** [comment]
Thank you.

**Comment by Weiming-Hu** [comment]
Hi. Could you kindly help me with [this issue](https://github.com/Weiming-Hu/Weiming-Hu.github.io/issues/1) when you are free? Many thanks.

**Comment by Weiming-Hu** [comment]
Hi. I've already solved this problem. Thank you!
