### ISSUE TITLE
Additional section in CV

### ISSUE THREAD

**Issue by Weiming-Hu** [mmistakes/jekyll-theme-basically-basic#57]
Hi,

I'm pretty new to the json-CV technique. I assume you are using a certain template if I understand it correctly. But how could I customize the CV template? For example, if I'd like to add a section for `presentations`, or `research products`, how could I do that?

Thank you.

**Comment by mmistakes** [comment]
Have you tried looking at the [`cv` layout](https://github.com/mmistakes/jekyll-theme-basically-basic/blob/master/_layouts/cv.html) and its [includes](https://github.com/mmistakes/jekyll-theme-basically-basic/tree/master/_includes/cv)? There's no magic there. It's taking the JSON file, assigning it as `cv` and then using dot notation looking up data using key/value pairs.

**Comment by Weiming-Hu** [comment]
Great. I'm going to create some additional html. Thank you.

**Comment by Weiming-Hu** [comment]
It works after I customized the cv.json file. Thank you!
