### ISSUE TITLE
Navigation lists twice the Home page, when home page has a title.

### ISSUE THREAD

**Issue by spygi** [mmistakes/jekyll-theme-basically-basic#63]
## Description
The home page is listed twice on the sidebar navigation, if it has a title.

## Environment
Jekyll 3.7.3 using the theme from Github pages, developed on MacOS 10.13.
On Github: github.com/spygi/tech-blog

## Expected behavior
Home page should be listed only once, either as "Home" or with the page title.

## Steps to reproduce the behavior
Just create a page with `layout: home` and give it a `title: Welcome`. Open the navigation bar and it will show both "Home" and "Welcome". This is not reproduced on your [example](https://mmistakes.github.io/jekyll-theme-basically-basic/) @mmistakes  because you use alt_title (which I would consider using for accessibility reasons).. 

Fix is live on tech.spygi.me, https://github.com/spygi/tech-blog/commit/60bed526ce310fbaa6b18375ce2fd963088837ff

See here together with my fix
![out](https://user-images.githubusercontent.com/4732694/40207585-8d13f946-5a35-11e8-853b-e4d1d1b34890.gif)

**Comment by spygi** [comment]
Not sure if "alt_title" is recommended here.. in any case if you agree with the change I can issue a proper PR :)
PS: thanks for your work!

**Comment by spygi** [comment]
Not sure why adding a title to a home page is considered an "edge case" but anyway, `alt_title` it is. Cheers

**Comment by mmistakes** [comment]
That's not an edge case. Having two "home" pages with `layout: home` is.
