### ISSUE TITLE
Tweak to docs ?

### ISSUE THREAD

**Issue by joncison** [mmistakes/jekyll-theme-basically-basic#64]
Thanks a million for providing this!

In your [docs](https://github.com/mmistakes/jekyll-theme-basically-basic#remove-the-unnecessary) you suggest to remove:

```.codeclimate.yml```

but I couldn't see this in the download.

I just mention it in case the docs need updating.

**Comment by mmistakes** [comment]
I removed Code Climate and didn't remove the reference to it in the docs. It's safe to ignore.
If you want to submit a pull request with that line removed from the documentation that would be great.

**Comment by joncison** [comment]
I tried to branch the repo so I could create the pull request (all via GitHub Desktop) but I got an "Authentication failed...." error.  Do I need permissions?  Forgive me if I ask dumb question ... :)

**Comment by mmistakes** [comment]
You can't directly fork or commit to this repo, that's probably why you're getting authentication errors.

What you need to do is "fork" this repo, which essentially makes a copy of it that you own. Then you can branch off of that, commit changes, then push it back up to GitHub... where you can then open a pull request against this repo.
