### ISSUE TITLE
How can I host this theme on GitHub Pages?

### ISSUE THREAD

**Issue by vhbsouza** [mmistakes/jekyll-theme-basically-basic#7]
I'm trying to push the theme to an gh-pages branch but jekyll complains about "_config.yml".
When I tried to move for an example, the contents of `example` or `docs` folder and commit and push to `gh-pages` it continues going wrong.

Can you help me?

**Comment by mmistakes** [comment]
I would take the contents of /docs/ and use that as the site you push to GitHub.

Then remove sample posts in /_posts/, remove or edit sample about.md and cv.md pages, customize _config.yml, /_data/ files, and you should be good to go.

**Comment by vhbsouza** [comment]
Thank You!!!
I think I've managed how to do it. It wasn't very intuitive, how about make an script to automize it for us?

**Comment by mmistakes** [comment]
A script is out of scope for this project. 

Once 3rd party themes are whitelisted for GitHub Pages it will be trivial to install/update. The whole fork a theme idea was a necessarily evil in the past but is horrible in practice. Dealing with merge conflicts just to update is a pain in the 🦋.

**Comment by vhbsouza** [comment]
@mmistakes , I don't understand how "fork a theme **was** a necessarily evil" if in the installation instructions you add this note.

> "Note: 3rd-party Ruby gem themes aren't currently supported on sites hosted with GitHub Pages. Basically Basic can still be used on GH Pages, but you will need to fork the theme instead. "

Actually, there is no other way to use the theme on GH Pages or am I wrong?
If I am, please explain.

.ps.: Sorry for my bad english. :disappointed:

**Comment by mmistakes** [comment]
I meant forking shouldn't be how Jekyll themes are installed. The new Ruby gem method is superior in so many ways, and that is the experience this theme was optimized for.

I'm hoping to push theme gems forward with this and hopefully nudge the [GitHub Pages](https://github.com/github/pages-gem) maintainers along to open up support for all 3rd party gems.

I only mentioned the forking method as it is the only way to use the them on GH. Most of my Jekyll themes use this method and it's less than ideal for everyone involved.

I plan on improving the documentation around forking the theme, but don't want to take away from the preferred method of installation.
