### ISSUE TITLE
Comments & Parmalink?

### ISSUE THREAD

**Issue by TheNewbieWoodworker** [mmistakes/jekyll-theme-basically-basic#72]
Is it possible to have Comments (Disqus) enabled on a page that has a permalink?

**Comment by mmistakes** [comment]
Disqus comments are supported for `post` and `page` layouts.

**Comment by TheNewbieWoodworker** [comment]
Thanks. Is this something I can change?

**Comment by TheNewbieWoodworker** [comment]
I mean, I can see where to change it - my question is, will this adversely affect anything else?

**Comment by mmistakes** [comment]
Yes. Just edit page.html to include these lines. 

https://github.com/mmistakes/jekyll-theme-basically-basic/blob/master/_layouts/post.html#L13-L15

Though you could save yourself the effort and just use `layout: post` for your pages. The two layouts are identical except for the Disqus comments Liquid conditional.

**Comment by TheNewbieWoodworker** [comment]
So you're saying I can use "layout: post" and if I don't put the file in the _posts folder, it won't be included in the list of posts?

**Comment by mmistakes** [comment]
Yup.

**Comment by TheNewbieWoodworker** [comment]
Awesome! Thanks!

**Comment by mmistakes** [comment]
Layout had nothing to do with if a file is considered a "post" or "page" or a "collection" by Jekyll.

**Comment by TheNewbieWoodworker** [comment]
Thanks for the info. To those of us who aren't Jekyll experts, it's confusing sometimes who's responsible for what. :)
