### ISSUE TITLE
Categories page lists full content of posts and not exercpts

### ISSUE THREAD

**Issue by twhite96** [mmistakes/jekyll-theme-basically-basic#73]
## Environment

Theme: 1.4.0
Jekyll: latest
GH Pages: No
Operating System: macOS 10.14
Repo: https://github.com/twhite96/thatmacnerd

## Expected behavior

Categories page lists posts with full content.

## Steps to reproduce the behavior

- Installed theme
- Setup theme
- Made categories page
- Set up front matter
- Categories page lists full content of posts with an unnecessary read more navigation button. I'd like to just show excerpts

## Other

Screencast:

![](https://cl.ly/8c418e8e41c2/Screen%252520Recording%2525202018-10-12%252520at%25252003.41%252520AM.gif)

**Comment by mmistakes** [comment]
This is happening on your older posts where you haven't assigned an `excerpt` in its YAML Front Matter. Either add excerpts as you have with your newer posts or use [Jekyll's excerpt tag](https://jekyllrb.com/docs/posts/#post-excerpts).
