### ISSUE TITLE
Change language post date

### ISSUE THREAD

**Issue by Funeoz** [mmistakes/jekyll-theme-basically-basic#75]
I would like to see the dates near the posts in French instead of English. I already changed the "lang" variable in "_config.yml" but I don't know how to change the date's language.

**Comment by mmistakes** [comment]
That's out of scope for this theme. Right now there isn't a good way to do it without hacking things up or using a i18n plugin. Unfortunately none of those are supported on GitHub Pages.

**Comment by qgustavor** [comment]
> Unfortunately none of those are supported on GitHub Pages.

In case someone else have this problem: if you consider [overwriting includes](https://github.com/mmistakes/jekyll-theme-basically-basic#overriding-includes-and-layouts) as "hacking things up" then just follow [one of those examples](http://alanwsmith.com/jekyll-liquid-date-formatting-examples) and overwrite `_includes/entry.html` and `_includes/page-intro.html`.

By the way, I don't think that any of those examples should be implemented in the theme, maybe some info about how overwrites can be used to translate things could be in the documentation.
