### ISSUE TITLE
Custom copyright statement in footer

### ISSUE THREAD

**Issue by cstoudt** [mmistakes/jekyll-theme-basically-basic#86]
I would like to add a custom copyright statement to the footer of my pages. 

Currently, the line reads: "© 2018 site-name"

I've been unable to figure out where this line is being generated.  How can I generate a custom line?

**Comment by cstoudt** [comment]
I found the solution: edit the _includes/footer.html file.

**Comment by mmistakes** [comment]
It's actually simpler than editing `footer.html`. Just add this to your `_config.yml` and change the copyright text to whatever you want.

```yaml
copyright: "Your copyright."
```

**Comment by cstoudt** [comment]
Thanks.  To get it to display exactly the way I want, I tweaked footer.html
and created a new variable in _config.yml for the text string.
