### ISSUE TITLE
Is it possible to create tooltips?

### ISSUE THREAD

**Issue by TheNewbieWoodworker** [mmistakes/jekyll-theme-basically-basic#89]
I may use the wrong terms here, so don't assume I know what I'm talking about. Is it possible to have a tooltip for a word in a blog entry? For example, if I use an acronym that the reader might not know, they could hover their mouse over the acronym, or else click the acronym, and the definition would "pop up" for them to read without leaving the current page?

If there's no built-in way, I saw this blog post (probably not jekyll-related), https://robots.thoughtbot.com/you-don-t-need-javascript-for-that, that shows how to do it with some scss, but I'm not sure if this would be usable in Jekyll.

Any thoughts? Thanks. Still loving the theme, by the way.

**Comment by mmistakes** [comment]
Not a feature of Jekyll. You could use a JavaScript library to do tooltips.

Or if you're just don't abbreviations you can write Kramdown flavored (Jekyll default) Markdown and it'll do `<abbr>` markup for you automatically, which on hover gives you the definition.

See Kramdowns docs for the syntax

https://kramdown.gettalong.org/syntax.html#abbreviations

**Comment by mmistakes** [comment]
And if you want to take it a step further you can style the `abbr` element so it works on tape for mobile devices.

https://bitsofco.de/making-abbr-work-for-touchscreen-keyboard-mouse/

**Comment by TheNewbieWoodworker** [comment]
Thanks, and it works great. Just what I was hoping for. Except... (there's always an except, right?) is there any way to adjust the delay before the overlay pops up? I thought it wasn't working at first, because you have to hover so long. Thanks again.

**Comment by mmistakes** [comment]
You're getting into JavaScript territory if you want to adjust that. The `abbr` overlay is part of the HTML spec that browser's interpret and present how they want.

If you want to change the look you need CSS. Everything else required JS.

**Comment by TheNewbieWoodworker** [comment]
Thanks. I'll look into it. The JavaScript is no problem, it's just that I never know where Jekyll/Markdown/Kramdown stop and HTML/(S)CSS/JS etc. start. I guess it's time for this retired Windows developer to learn some new tricks. At least I'm doing it on a Mac and not a Windows machine, thank God. Shudder. Never again, even if it did pay my bills.

Thanks again.
