### ISSUE TITLE
Subscription and notification of new posts

### ISSUE THREAD

**Issue by thepredictionlab** [mmistakes/jekyll-theme-basically-basic#91]
When one pushes the "subscribe" button, you get navigated to an atom.xml file, which is not what I was expecting. I was hoping people could enter an email address to receive  notifications of a new post. Was this the intent behind the subscribe button? Is this functionality possible?? Thanks!

**Comment by mmistakes** [comment]
This functionality isn't possible without other integrations... which is out of the scope of the theme.
I'm simply mimic'ing the same feature Jekyll's default theme Minima does.

Their subscribe link points to an XML feed as well.
