### ISSUE TITLE
Instagram?

### ISSUE THREAD

**Issue by TheNewbieWoodworker** [mmistakes/jekyll-theme-basically-basic#92]
Is there a way to specify my Instagram ID? I see there's an include file "_includes/icon-instagram.html", but I don't see it referenced anywhere (but I could be wrong).

Also, would you prefer I ask questions like this here, or over on the jekyll talk forum? Thanks.

**Comment by mmistakes** [comment]
Yes and no. The icons are included, but you need to customize [`_includes/contact-list.html`](https://github.com/mmistakes/jekyll-theme-basically-basic/blob/master/_includes/contact-list.html#L11-L17) to pull in Instagram or any other social network (currently the theme only shows Twitter and Github).

The documentation mentions how to include other icons. https://github.com/mmistakes/jekyll-theme-basically-basic#svg-icons

You'd essentially add this and it'll include the icon and link:

```
{% include icon-instagram.html username='yourUsername' label='Instagram' %}
```

**Comment by TheNewbieWoodworker** [comment]
Thanks. I added this:

```
  {% if site.instagram_username %}
    <li>{% include icon-instagram.html username=site.instagram_username label='Instagram' %}</li>
  {% endif %}
```

And it works.

If I wanted the social media icons in the header or footer, would it be a lot of work, or is there another theme I could steal from?

Thanks again.

**Comment by mmistakes** [comment]
For [the footer](https://github.com/mmistakes/so-simple-theme/blob/master/_includes/footer.html#L4-L15) you can steal from my other theme, [**So Simple**](https://github.com/mmistakes/so-simple-theme).

**Comment by TheNewbieWoodworker** [comment]
Perfect. Thanks. You didn't answer my other question - do you prefer questions here or on jekyll talk?

**Comment by mmistakes** [comment]
I'd prefer Jekyll Talk so maybe others from the community could jump in and help if it's basic Jekyll stuff.
But generally people have more specific asks so in those cases makes more sense here.

**Comment by TheNewbieWoodworker** [comment]
OK, thanks. Sometimes I don't know which it is, but I'll figure it out. I truly appreciate your timely responses.
