### ISSUE TITLE
Usability Issues from Google Search Console

### ISSUE THREAD

**Issue by TheNewbieWoodworker** [mmistakes/jekyll-theme-basically-basic#96]
I received an email from Google Search Console titled "Mobile Usability issues detected for site https://thenewbiewoodworker.com/". Here's the issues, which are all listed as being on the landing page:

- Content wider than screen
- Text too small to read
- Clickable elements too close together

I checked the website on my iPhone, and other than the Action buttons being close together (but still usable, as far as I'm concerned), I couldn't see anything wrong.

I'm using GitHub pages. I *think* I have the current source for Basically Basic, but I don't know how to find the version number.

I don't *think* I did anything to cause this, but anything's possible.

Have you seen this before? Any ideas what to do about it?

Sorry I filed this under "bug report". I wasn't sure which category it belonged under. Thanks.

**Comment by mmistakes** [comment]
In my experience the big G can be overly aggressive with these "suggestions". Some end up being false positives... like the content being too wide one.

I wouldn't lose sleep over any of these.

If you want more detail use Chrome's web developer tools and check the Audit tab. It'll run these same tests and indicate exactly where the issues are.

Usually it flags footer links that are often purposely styled smaller. Or it gets confused by "hidden" nav links that are only visible for assitive tech or if you tab through the page.

**Comment by TheNewbieWoodworker** [comment]
Thanks you for the reply. I figured it wasn't a big deal. I find it interesting that it hadn't happened until now, but I _did_ make some changes to the home page, so maybe that's it. I will definitely check it out in Chrome.

Question, if you know: Does Google do anything negative based on these warnings, like lower me in search results or anything like that? Not that it would make a huge difference with my site, but I'm curious.

Thanks again,

**Comment by mmistakes** [comment]
You'll see these sorts of things depending on when Google decides to crawl your site and report back.
You'd be better off searching out resources and sites dedicated to SEO. You'll find yourself going down a really deep rabbit hole as there's a lot to learn and a lot of voodoo as Google isn't always transparent with this stuff.

**Comment by TheNewbieWoodworker** [comment]
LOL - I looked at a couple of things after I replied, and I came to that conclusion almost instantly. I don't have time for a rabbit trail right now. 😛Thanks!
