### ISSUE TITLE
Request for Hidden Scrollbar when Sidebar is populated with items

### ISSUE THREAD

**Issue by DarkAbhi** [mmistakes/jekyll-theme-basically-basic#97]
Hi,
When the sidebar is populated or as a twitter feed like in this screenshot. Would be nice to get rid of the ugly scrollbar and just the mouse scrolling working anyway.
![Screenshot from 2019-04-19 21-17-27](https://user-images.githubusercontent.com/22658573/56431786-afa0da80-62e8-11e9-9df9-e994dac46e39.png)

**Comment by mmistakes** [comment]
How would a keyboard user scroll the container if the scrolling is removed?

A lot of this is dependent on the browser. I believe Safari doesn't even show a scrollbar until you try to scroll the content with touch or a pointing device.

**Comment by DarkAbhi** [comment]
Yes it would be browser dependent. But I've come across sites where the scrollbar is hidden and scrolling does take effect. I was wondering if it is possible?

**Comment by mmistakes** [comment]
Do you have any examples of sites that do this?

**Comment by DarkAbhi** [comment]
Well they were personal websites of users, I don't remember them around 3-4.

https://kunalkene1797.github.io/ 
This user has his twitter feed on his sidebar and I took a liking to it and tried it here.

https://html5up.net/prologue
This was previously a template I used to tinker around with and this sidebar would hide the Scroll Bar

**Comment by mmistakes** [comment]
Both have scrollbars though.

![image](https://user-images.githubusercontent.com/1376749/56597604-cf722000-65c0-11e9-84d6-6ebd2ec7eafa.png)

![image](https://user-images.githubusercontent.com/1376749/56597632-dac54b80-65c0-11e9-847e-00175ecedb16.png)

**Comment by DarkAbhi** [comment]
what even? Last I used that template it kept my Sidenav bar scrollbar hidden. But that user site is fine on mine 
![image](https://user-images.githubusercontent.com/22658573/56598339-f3aa1d00-6611-11e9-9c94-0597164fc7e3.png)

Here's a video : https://streamable.com/hjlgu

Firefox 66.0.3
