### ISSUE TITLE
Center aligning the main content

### ISSUE THREAD

**Issue by 8hantanu** [mmistakes/jekyll-theme-basically-basic#98]
In higher resolution screens the right-hand space feels quite empty when everything is left aligned.
I would like to center align the contents of the home page and the post page.
So, it should look something like this.

![Home Page](https://user-images.githubusercontent.com/19494743/57380060-c63ea100-71c5-11e9-89c8-3ee2078fd21b.png)

![Post page](https://user-images.githubusercontent.com/19494743/57380066-cc348200-71c5-11e9-90eb-8c11ca034217.png)

How can I achieve the above? Thank you.

**Comment by 8hantanu** [comment]
Thank you, that worked. BTW I really liked your tiny paintings. :smile:

**Comment by mmistakes** [comment]
Add `margin-left: auto;` and `margin-right: auto;` to the `.inner` element via CSS and it'll center those elements like you want.

```
.inner {
  max-width: $large;
  margin-left: auto;
  margin-right: auto;
}
```

ref: https://github.com/mmistakes/jekyll-theme-basically-basic/blob/master/_sass/basically-basic/_layout.scss#L59-L61

**Comment by mehulg25** [comment]
Hi!
How can I keep the hero image aligned to the left while making the content centre aligned?
@mmistakes @8hantanu

**Comment by JustTheBek** [comment]
> Add `margin-left: auto;` and `margin-right: auto;` to the `.inner` element via CSS and it'll center those elements like you want.
> 
> ```css-scss
> .inner {
>   max-width: $large;
>   margin-left: auto;
>   margin-right: auto;
> }
> ```
> 
> ref: https://github.com/mmistakes/jekyll-theme-basically-basic/blob/master/_sass/basically-basic/_layout.scss#L59-L61

Thank you it worked for me as well! I have an other question: Do you know how I could make the content wider? It looks a bit strange that I have such huge margins and the content is shrunk in the middle.
Thank you in advance! : )
