### ISSUE TITLE
Sharing on Facebook does not include post image?

### ISSUE THREAD

**Issue by TheNewbieWoodworker** [mmistakes/jekyll-theme-basically-basic#99]
When I put an image as the first thing in a post, it shows up in the post excerpts, which is awesome.

![image](https://user-images.githubusercontent.com/36159830/59437691-e524ea00-8da6-11e9-973f-51a90d86e741.png)

But when I share the post on Facebook, Facebook doesn't show the image.

![image](https://user-images.githubusercontent.com/36159830/59437777-0b4a8a00-8da7-11e9-9975-e041bfba7d56.png)

Any ideas why it's not showing the image?

BTW, I'm sharing my posts on Facebook using the following code, which I'm sure I harvested from somewhere on the Net:

```html
    <a href="https://www.facebook.com/sharer/sharer.php?u={{ page.url | absolute_url | url_encode }}" onclick="window.open(this.href, 'window', 'left=20,top=20,width=500,height=500,toolbar=1,resizable=0'); return false;" title="Share on Facebook">
      <span class="icon icon--facebook">{% include icon-facebook.svg %}</span>
      <span class="label">Facebook</span>
    </a>
```
Thanks!

**Comment by mmistakes** [comment]
Facebook uses the content found in OpenGraph meta tags to populate their share widgets.
The theme make's use of [jekyll-seo-tag](url
![image](https://user-images.githubusercontent.com/1376749/59439268-f24fd200-8dc2-11e9-9a6f-35b5087ccf87.png)
) which will add OpenGraph meta tags to your `<head>`. Images are added when you define one a [large full-width image](https://github.com/mmistakes/jekyll-theme-basically-basic#images) via a post/page's YAML Front Matter.

Simply adding an image to the body won't add it as an image to OG tags. 

You can use the [OpenGraph debugger](https://developers.facebook.com/tools/debug/) tool to see what meta data it infers about your page. I don't think they're parser grabs images in the main content. And if it does it could be picky about the image's dimensions and resolution. In my experience they don't always show your images even when you specify them using the OG image meta tag.

**Comment by TheNewbieWoodworker** [comment]
Perfect. Thanks for the answer.

**Comment by thatvirtualboy** [comment]
@TheNewbieWoodworker Would you mind sharing how you got images working in the excerpts?

**Comment by TheNewbieWoodworker** [comment]
After the front matter, I put the image and follow it with 2 breaks `<br/>`, then my initial paragraph. I don't think I changed anything else. If this doesn't work for you, let me know.

**Comment by thatvirtualboy** [comment]
Thanks for the reply @TheNewbieWoodworker. Seems something else had to have been changed. That doesn't appear to affect my excerpts, and @mmistakes has stated this theme doesn't support this feature out of the box.

**Comment by mmistakes** [comment]
I think it depends on how you're doing excerpts with Jekyll. If you look at some of the demo posts I'm not assigning an `excerpt` in the front matter. This signals to Jekyll to use it's automatic excerpt generator which converts the first paragraphs of a post's `content` into an excerpt.

If you have Markdown images in this paragraph it will show up in the post listings. If you assigned an `excerpt` in the post's front matter than it will ignore it... which is probably what's happening for you.

https://jekyllrb.com/docs/posts/#post-excerpts

https://mmistakes.github.io/jekyll-theme-basically-basic/page2/

https://github.com/mmistakes/jekyll-theme-basically-basic/blob/master/docs/_posts/2010-06-02-post-video-youtube.md

![image](https://user-images.githubusercontent.com/1376749/76762629-fe106080-6767-11ea-8bc4-b7ab69b61f88.png)

**Comment by thatvirtualboy** [comment]
You guys are absolutely right. I had the 'excerpt' section in my front matter which was blocking everything I was trying. Once I removed that and tested with the image first then breaks, it generates the native excerpt as expected. Look good! 👍 Thanks!
